server:
  port: 8000

database:
  username: GnomDanon
  password: SpringStore123

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

---

spring:
  profiles: prod

---

spring:
  profiles: test