server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring2023
    username: postgres
    password: Ural-Revda23
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

#---
#
#spring:
#  profiles: dev
#
#---
#
#spring:
#  profiles: prod
#
#---
#
#spring:
#  profiles: test